# Generated by Django 3.0.4 on 2020-04-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hit_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='hit_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('s_description', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('hash_tags', models.CharField(max_length=500)),
                ('private', models.BooleanField(default=False)),
                ('book_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('img_link', models.CharField(default=None, max_length=356)),
            ],
        ),
    ]
