# Generated by Django 3.0.4 on 2020-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit_post',
            name='counter',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='hit_post',
            name='custom_message',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='hit_post',
            name='period',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='hit_post',
            name='time_for_next_email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
