# Generated by Django 3.0.4 on 2020-04-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit_book', '0002_auto_20200412_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit_post',
            name='counter',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
