# Generated by Django 3.0.4 on 2020-04-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit_book', '0003_auto_20200412_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit_post',
            name='counter',
            field=models.CharField(default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hit_post',
            name='custom_message',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hit_post',
            name='period',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hit_post',
            name='time_for_next_email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
