# Generated by Django 3.0.4 on 2020-04-14 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hit_book', '0005_auto_20200412_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit_post',
            name='hash_tags',
        ),
        migrations.RemoveField(
            model_name='hit_post',
            name='private',
        ),
    ]
